# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "fedora/32-cloud-base"
NODE_COUNT = 2
CPU_COUNT = 1
MEMORY_COUNT_MIN = 768
MEMORY_COUNT_MAX = 1024

Vagrant.configure("2") do |config|
  config.vm.define "haproxy" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
    subconfig.vm.hostname = "haproxy"
    subconfig.vm.provider :libvirt do |libvirt|
      libvirt.cpus = CPU_COUNT
      libvirt.memory = MEMORY_COUNT_MAX
    end
  end
  
  (1..NODE_COUNT).each do |i|
    config.vm.define "srv#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "srv#{i}"
      subconfig.vm.provider :libvirt do |libvirt|
        libvirt.cpus = CPU_COUNT
        libvirt.memory = MEMORY_COUNT_MIN
      end
    end
  end
end
